In [1]:
import numpy as np

In [3]:
arr = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [4]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arr[0]

array([ 5, 10, 15])

In [9]:
arr[2][2]

45

In [10]:
arr[1][0]

20

In [13]:
np.random.randn(2,5)

array([[ 0.10427053, -0.72283292,  0.25831537, -1.82117241,  0.18771956],
       [-0.83389354,  0.6227703 , -0.31214041,  0.06757623,  0.24792178]])

In [14]:
arr[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [15]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [16]:
arr[1,2]

30

In [17]:
arr[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [18]:
arr[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [19]:
arr[:2,1:]

array([[10, 15],
       [25, 30]])

In [36]:
arr[:0,:1]

array([], shape=(0, 1), dtype=int64)

In [37]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
list = [1,2,3,4,5]

In [26]:
list

[1, 2, 3, 4, 5]

In [27]:
list[0]

1

In [28]:
lists = np.array(list)

In [29]:
lists

array([1, 2, 3, 4, 5])

In [30]:
lists[0]

1

In [38]:
aar

NameError: name 'aar' is not defined

In [39]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr >10

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [43]:
arr[arr>10]

array([15, 20, 25, 30, 35, 40, 45])

In [44]:
joe = np.arange(50).reshape(5,10)

In [57]:
joe

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
joe[0:,0:1]

array([[ 0],
       [10],
       [20],
       [30],
       [40]])